[tool.qpro]
[[tool.qpro.server_targets]]
user = ""
host = ""
port = 22
path = ""

[tool.qpro.config]
build = ""
entry_point = "main.c"
executable = "python3 -m QproCTemplateCommander.main"
input_file = "dist/input.txt"
template_root = "template/"
enable_complete = true
